<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="3.0" xmlns:ns0="io.kaoto.datamapper.poc.test">
    <xsl:output method="xml" indent="yes"/>
    <xsl:template match="/">
        <ShipOrder xmlns="io.kaoto.datamapper.poc.test">
            <xsl:attribute name="OrderId">
                <xsl:value-of select="/ns0:ShipOrder/@OrderId"/>
            </xsl:attribute>
            <xsl:for-each select="/ns0:ShipOrder/Item">
                <Item xmlns="">
                    <Title xmlns="">
                        <xsl:value-of select="Title"/>
                    </Title>
                </Item>
            </xsl:for-each>
            <xsl:for-each select=""/>
        </ShipOrder>
    </xsl:template>
</xsl:stylesheet>
